wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_acc_step
      5: 1
      6:
      - 1
    - 1: train_f1_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    - 1: val_f1
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_acc_epoch
      5: 1
      6:
      - 1
    - 1: train_f1_epoch
      5: 1
      6:
      - 1
    python_version: 3.9.11
    start_time: 1657626125
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 23
      4: 3.9.11
      5: 0.12.21
      6: 4.17.0
      8:
      - 2
      - 3
      - 5
